In [1]:
import numpy as np

In [9]:
a = np.arange(15)

In [10]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [11]:
a = a.reshape(3,5)

In [12]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [13]:
a.ndim

2

In [14]:
a.shape

(3, 5)

In [15]:
a.size

15

In [16]:
a.dtype.name

'int32'

In [17]:
a.itemsize

4

In [18]:
type(a)

numpy.ndarray

In [19]:
b = np.array([1,2,3])

In [20]:
type(b)

numpy.ndarray

In [21]:
a.dtype

dtype('int32')

In [22]:
b = np.array([1.2, 3.5, 5.1])

In [23]:
b.dtype

dtype('float64')

In [24]:
np.array([(1.5, 2, 3), (4, 5, 6)])

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [26]:
a=np.ones((2, 3, 4), dtype=np.int16)

In [27]:
a

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [28]:
a.ndim

3

In [29]:
a.shape

(2, 3, 4)

In [30]:
a.size

24

In [31]:
np.empty((2,3))

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [33]:
x = np.linspace(0, 2 * np.pi, 100)        # useful to evaluate function at lots of points
f = np.sin(x)

In [34]:
f

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

In [35]:
c = np.arange(24).reshape(2, 3, 4)

In [36]:
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [37]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)

In [38]:
b

array([0, 1, 2, 3])

In [39]:
b**2

array([0, 1, 4, 9], dtype=int32)

In [40]:
np.sin(a)

array([ 0.91294525, -0.98803162,  0.74511316, -0.26237485])

In [41]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [42]:
a<35

array([ True,  True, False, False])

In [43]:
a[a<35]

array([20, 30])

In [44]:
A = np.array([[1, 1],
              [0, 1]])
B = np.array([[2, 0],
              [3, 4]])

In [45]:
A

array([[1, 1],
       [0, 1]])

In [47]:
B

array([[2, 0],
       [3, 4]])

In [49]:
A*B  # element wise

array([[2, 0],
       [0, 4]])

In [50]:
A@B #matrix product

array([[5, 4],
       [3, 4]])

In [51]:
A.dot(B)  #matrix product

array([[5, 4],
       [3, 4]])

In [52]:
rg = np.random.default_rng(1)

In [53]:
rg

Generator(PCG64) at 0x1CA8C2CF660

In [54]:
a = np.ones((2,3), dtype=int)

In [55]:
a

array([[1, 1, 1],
       [1, 1, 1]])

In [62]:
b = rg.random((2, 3))

In [57]:
b

array([[0.51182162, 0.9504637 , 0.14415961],
       [0.94864945, 0.31183145, 0.42332645]])

In [58]:
a*=3

In [59]:
a

array([[3, 3, 3],
       [3, 3, 3]])

In [63]:
b+=a

In [64]:
b

array([[3.82770259, 3.40919914, 3.54959369],
       [3.02755911, 3.75351311, 3.53814331]])

In [65]:
a+=b

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

In [66]:
a = np.ones(3,dtype = np.int32)

In [67]:
b = np.linspace(0,np.pi,3)

In [69]:
b.dtype.name

'float64'

In [70]:
c = a+b

In [71]:
c

array([1.        , 2.57079633, 4.14159265])

In [72]:
c.dtype

dtype('float64')

In [73]:
d = np.exp(c * 1j)

In [74]:
d

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [75]:
d.dtype

dtype('complex128')

In [76]:
a = rg.random((2, 3))

In [77]:
a

array([[0.32973172, 0.7884287 , 0.30319483],
       [0.45349789, 0.1340417 , 0.40311299]])

In [78]:
a.sum()

2.412007822394087

In [79]:
a.min()

0.13404169724716475

In [80]:
a.max()

0.7884287034284043

In [81]:
b = np.arange(12).reshape(3, 4)

In [82]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [83]:
b.sum(axis=0)  # sum of each column

array([12, 15, 18, 21])

In [85]:
b.sum(axis=1)  # sum of each row

array([ 6, 22, 38])

In [86]:
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)

In [88]:
b.sum()  # sum of all elements

66

In [89]:
b.max(axis=0)

array([ 8,  9, 10, 11])

In [9]:
a = np.arange(10)

In [10]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
a=a**3

In [12]:
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [13]:
a[2:6]

array([  8,  27,  64, 125], dtype=int32)

In [15]:
a[:6:2]=1000

In [16]:
a

array([1000,    1, 1000,   27, 1000,  125,  216,  343,  512,  729],
      dtype=int32)

In [17]:
a[::-1]

array([ 729,  512,  343,  216,  125, 1000,   27, 1000,    1, 1000],
      dtype=int32)

In [18]:
for i in a:
    print(i**(1/3.0))

9.999999999999998
1.0
9.999999999999998
3.0
9.999999999999998
5.0
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


In [19]:
def f(x, y):
    return 10 * x + y

b = np.fromfunction(f, (5, 4), dtype=int)

In [20]:
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [21]:
c = np.fromfunction(lambda x,y: 10*x+y, (5,4), dtype=int)

In [22]:
c

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [23]:
b[2,3]

23

In [24]:
b[0:5,1]

array([ 1, 11, 21, 31, 41])

In [25]:
b[1:3,:]

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [26]:
b[-1]

array([40, 41, 42, 43])

In [27]:
b[-1,:]

array([40, 41, 42, 43])

In [28]:
c = np.array([[[  0,  1,  2],  # a 3D array (two stacked 2D arrays)
               [ 10, 12, 13]],
              [[100, 101, 102],
               [110, 112, 113]]])

In [29]:
c.shape

(2, 2, 3)

In [30]:
c[1]

array([[100, 101, 102],
       [110, 112, 113]])

In [31]:
c[1,...]

array([[100, 101, 102],
       [110, 112, 113]])

In [35]:
c[1,:,:]

array([[100, 101, 102],
       [110, 112, 113]])

In [36]:
c[...,2]

array([[  2,  13],
       [102, 113]])

In [38]:
c[...,1]

array([[  1,  12],
       [101, 112]])

In [39]:
c[...,0]

array([[  0,  10],
       [100, 110]])

In [40]:
c[:,:,2]

array([[  2,  13],
       [102, 113]])

In [41]:
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [43]:
for element in b.flat:
    print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


In [45]:
rg = np.random.default_rng(1)
a = np.floor(10 * rg.random((3, 4)))

In [46]:
a

array([[5., 9., 1., 9.],
       [3., 4., 8., 4.],
       [5., 0., 7., 5.]])

In [47]:
a.ravel()

array([5., 9., 1., 9., 3., 4., 8., 4., 5., 0., 7., 5.])

In [48]:
a.reshape(2,6)

array([[5., 9., 1., 9., 3., 4.],
       [8., 4., 5., 0., 7., 5.]])

In [49]:
a.T

array([[5., 3., 5.],
       [9., 4., 0.],
       [1., 8., 7.],
       [9., 4., 5.]])

In [50]:
a.T.shape

(4, 3)

In [51]:
a.ravel().shape

(12,)

In [52]:
a.resize(2,6)

In [53]:
a

array([[5., 9., 1., 9., 3., 4.],
       [8., 4., 5., 0., 7., 5.]])

In [55]:
a.reshape(3,-1)

array([[5., 9., 1., 9.],
       [3., 4., 8., 4.],
       [5., 0., 7., 5.]])

In [56]:
a = np.floor(10 * rg.random((2, 2)))

In [57]:
b = np.floor(10 * rg.random((2, 2)))

In [58]:
a

array([[3., 7.],
       [3., 4.]])

In [59]:
b

array([[1., 4.],
       [2., 2.]])

In [60]:
np.vstack((a,b))

array([[3., 7.],
       [3., 4.],
       [1., 4.],
       [2., 2.]])

In [61]:
np.hstack((a,b))

array([[3., 7., 1., 4.],
       [3., 4., 2., 2.]])

In [62]:
from numpy import newaxis

In [64]:
np.column_stack((a,b))

array([[3., 7., 1., 4.],
       [3., 4., 2., 2.]])

In [65]:
a = np.array([4., 2.])
b = np.array([3., 8.])

In [66]:
np.column_stack((a,b))

array([[4., 3.],
       [2., 8.]])

In [67]:
np.hstack((a,b))

array([4., 2., 3., 8.])

In [68]:
a[:,newaxis]

array([[4.],
       [2.]])